name: Deploy Bing Wallpaper

on:
  schedule:
    - cron: '*/10 * * * *' # 每10分钟检查一次 (UTC时间)
  workflow_dispatch: # 允许手动触发
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Fetch Bing Image
      run: |
        mkdir -p pic json api/today
        python fetch_bing.py
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        keep_files: false
